<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZyMvUK4\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZyMvUK4/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZyMvUK4.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZyMvUK4\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZyMvUK4\App_KernelDevDebugContainer([
    'container.build_hash' => 'ZyMvUK4',
    'container.build_id' => 'ffea408a',
    'container.build_time' => 1593438024,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZyMvUK4');
